name: Stay at Home For Life
favicon: null
layout_spectrum: 0.87864
typography_spectrum: 0.56335
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.11393791297450662
  lightness: 0.013835991499945521
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
